### ISSUE TITLE
 org.gnome.Platform//42 is end-of-life

### ISSUE THREAD

**Issue by rusty-snake** [flathub/org.gnome.Mines#9]
The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.

**Comment by Mershl** [comment]
The update does not seem to pop up on flathub.

**Comment by bbhtt** [comment]
The publish job failed https://buildbot.flathub.org/#/builders/6/builds/30114

ping @evfool, please re-trigger a build there (https://buildbot.flathub.org/#/apps/org.gnome.Mines > start build).

**Comment by evfool** [comment]
Done, started another build.
